import { Asset } from './assetManifest';

export const EXPANSION_ASSETS: Partial<Asset>[] = [
  // BOARD / ENVIRONMENT
  { id: 'tile-luminance-1', stage: 'B', category: 'board', name: 'Tile Luminance 1', description: 'Tile variant with luminance level 1', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'tile-luminance-2', stage: 'B', category: 'board', name: 'Tile Luminance 2', description: 'Tile variant with luminance level 2', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'tile-luminance-3', stage: 'B', category: 'board', name: 'Tile Luminance 3', description: 'Tile variant with luminance level 3', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'tile-luminance-4', stage: 'B', category: 'board', name: 'Tile Luminance 4', description: 'Tile variant with luminance level 4', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'tile-luminance-5', stage: 'B', category: 'board', name: 'Tile Luminance 5', description: 'Tile variant with luminance level 5', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'powerpoint-idle', stage: 'B', category: 'board', name: 'Powerpoint Idle', description: 'Strategic powerpoint in idle state', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'powerpoint-active', stage: 'B', category: 'board', name: 'Powerpoint Active', description: 'Strategic powerpoint in active state', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'powerpoint-healing', stage: 'B', category: 'board', name: 'Powerpoint Healing', description: 'Strategic powerpoint with healing aura', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'powerpoint-light-owned', stage: 'B', category: 'board', name: 'Powerpoint Light Owned', description: 'Powerpoint controlled by Light faction', type: 'image', faction: 'light', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'powerpoint-dark-owned', stage: 'B', category: 'board', name: 'Powerpoint Dark Owned', description: 'Powerpoint controlled by Dark faction', type: 'image', faction: 'dark', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'overlay-legal-move', stage: 'B', category: 'board', name: 'Overlay Legal Move', description: 'Grid overlay for legal movement', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'overlay-illegal-move', stage: 'B', category: 'board', name: 'Overlay Illegal Move', description: 'Grid overlay for illegal movement', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'overlay-attack', stage: 'B', category: 'board', name: 'Overlay Attack', description: 'Grid overlay for attack range', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'overlay-selected', stage: 'B', category: 'board', name: 'Overlay Selected', description: 'Grid overlay for selected tile', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'overlay-danger', stage: 'B', category: 'board', name: 'Overlay Danger', description: 'Grid overlay for danger zones', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'board-coordinates', stage: 'B', category: 'board', name: 'Board Coordinates', description: 'Alphanumeric board coordinate markers', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'arena-neutral', stage: 'B', category: 'board', name: 'Arena Neutral', description: 'Neutral combat arena background', type: 'image', model_id: 'gemini-3-pro-image-preview' },
  { id: 'barrier-solid', stage: 'B', category: 'board', name: 'Barrier Solid', description: 'Solid physical barrier object', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'barrier-phased', stage: 'B', category: 'board', name: 'Barrier Phased', description: 'Ethereal phased barrier object', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'barrier-light', stage: 'B', category: 'board', name: 'Barrier Light', description: 'Light-infused barrier object', type: 'image', faction: 'light', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'barrier-dark', stage: 'B', category: 'board', name: 'Barrier Dark', description: 'Dark-infused barrier object', type: 'image', faction: 'dark', model_id: 'gemini-3.1-flash-image-preview' },

  // SPELLS
  { id: 'spell-shift-time', stage: 'D', category: 'spell', name: 'Spell Shift Time', description: 'Icon for time manipulation spell', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'spell-exchange', stage: 'D', category: 'spell', name: 'Spell Exchange', description: 'Icon for position exchange spell', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'spell-summon-elemental', stage: 'D', category: 'spell', name: 'Spell Summon Elemental', description: 'Icon for elemental summoning', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'spell-revive', stage: 'D', category: 'spell', name: 'Spell Revive', description: 'Icon for unit revival spell', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'spell-imprison', stage: 'D', category: 'spell', name: 'Spell Imprison', description: 'Icon for unit imprisonment spell', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'spell-teleport-used', stage: 'D', category: 'spell', name: 'Spell Teleport Used', description: 'Exhausted state for teleport spell', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'spell-heal-used', stage: 'D', category: 'spell', name: 'Spell Heal Used', description: 'Exhausted state for heal spell', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'spell-shift-time-used', stage: 'D', category: 'spell', name: 'Spell Shift Time Used', description: 'Exhausted state for shift time spell', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'spell-exchange-used', stage: 'D', category: 'spell', name: 'Spell Exchange Used', description: 'Exhausted state for exchange spell', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'spell-summon-elemental-used', stage: 'D', category: 'spell', name: 'Spell Summon Elemental Used', description: 'Exhausted state for summon spell', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'spell-revive-used', stage: 'D', category: 'spell', name: 'Spell Revive Used', description: 'Exhausted state for revive spell', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'spell-imprison-used', stage: 'D', category: 'spell', name: 'Spell Imprison Used', description: 'Exhausted state for imprison spell', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },

  // STATUS / FX
  { id: 'status-imprisoned', stage: 'D', category: 'spell', name: 'Status Imprisoned', description: 'Status icon for imprisoned units', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'status-cannot-cast', stage: 'D', category: 'spell', name: 'Status Cannot Cast', description: 'Status icon for silenced units', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'status-on-powerpoint', stage: 'D', category: 'spell', name: 'Status On Powerpoint', description: 'Status icon for units on powerpoints', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'status-selected', stage: 'D', category: 'spell', name: 'Status Selected', description: 'Selection highlight status', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'status-legal', stage: 'D', category: 'spell', name: 'Status Legal', description: 'Indicator for legal move target', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'status-illegal', stage: 'D', category: 'spell', name: 'Status Illegal', description: 'Indicator for illegal move target', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'status-danger', stage: 'D', category: 'spell', name: 'Status Danger', description: 'Indicator for dangerous tile', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'status-objective-control', stage: 'D', category: 'spell', name: 'Status Objective Control', description: 'Indicator for objective ownership', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'fx-teleport', stage: 'D', category: 'spell', name: 'FX Teleport', description: 'Visual effect for teleportation', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'fx-heal', stage: 'D', category: 'spell', name: 'FX Heal', description: 'Visual effect for healing', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'fx-imprison', stage: 'D', category: 'spell', name: 'FX Imprison', description: 'Visual effect for imprisonment', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'fx-luminance-shift', stage: 'D', category: 'spell', name: 'FX Luminance Shift', description: 'Visual effect for luminance change', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'fx-magic-bolt', stage: 'D', category: 'spell', name: 'FX Magic Bolt', description: 'Visual effect for magic projectile', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'fx-fire-burst', stage: 'D', category: 'spell', name: 'FX Fire Burst', description: 'Visual effect for fire explosion', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'fx-stone-impact', stage: 'D', category: 'spell', name: 'FX Stone Impact', description: 'Visual effect for earth impact', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'fx-shadow-pulse', stage: 'D', category: 'spell', name: 'FX Shadow Pulse', description: 'Visual effect for dark pulse', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'fx-holy-flare', stage: 'D', category: 'spell', name: 'FX Holy Flare', description: 'Visual effect for light flare', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'fx-poison', stage: 'D', category: 'spell', name: 'FX Poison', description: 'Visual effect for poison/acid', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'combat-projectile-light', stage: 'D', category: 'spell', subcategory: 'projectile', name: 'Projectile Light', description: 'Sacred golden bolt fired by a Light faction ranged unit', type: 'image', faction: 'light', requiresCutout: true, model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'combat-projectile-dark', stage: 'D', category: 'spell', subcategory: 'projectile', name: 'Projectile Dark', description: 'Shadow void bolt fired by a Dark faction ranged unit', type: 'image', faction: 'dark', requiresCutout: true, model_id: 'gemini-3.1-flash-image-preview' },

  // UI
  { id: 'ui-button-hover', stage: 'E', category: 'ui', name: 'UI Button Hover', description: 'Button hover state', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'ui-button-pressed', stage: 'E', category: 'ui', name: 'UI Button Pressed', description: 'Button pressed state', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'ui-button-disabled', stage: 'E', category: 'ui', name: 'UI Button Disabled', description: 'Button disabled state', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'ui-tab', stage: 'E', category: 'ui', name: 'UI Tab', description: 'Tab navigation element', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'ui-toggle', stage: 'E', category: 'ui', name: 'UI Toggle', description: 'Toggle switch element', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'ui-slider', stage: 'E', category: 'ui', name: 'UI Slider', description: 'Slider bar element', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'ui-tooltip', stage: 'E', category: 'ui', name: 'UI Tooltip', description: 'Tooltip popup frame', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'ui-modal', stage: 'E', category: 'ui', name: 'UI Modal', description: 'Modal window frame', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'ui-healthbar', stage: 'E', category: 'ui', name: 'UI Healthbar', description: 'Health bar frame and fill', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'ui-turn-banner', stage: 'E', category: 'ui', name: 'UI Turn Banner', description: 'Large turn transition banner', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'ui-codex-page', stage: 'E', category: 'ui', name: 'UI Codex Page', description: 'Background for codex/lore pages', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'ui-endgame-frame', stage: 'E', category: 'ui', name: 'UI Endgame Frame', description: 'Frame for victory/defeat screen', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },
  { id: 'ui-cursor', stage: 'E', category: 'ui', name: 'UI Cursor', description: 'Custom game cursor', type: 'image', model_id: 'gemini-3.1-flash-image-preview' },

  // AUDIO
  { id: 'music-defeat-cue', stage: 'F', category: 'music', name: 'Music Defeat Cue', description: 'Short defeat stinger', type: 'audio', model_id: 'lyria-3-clip-preview' },
  { id: 'music-codex-ambience', stage: 'F', category: 'music', name: 'Music Codex Ambience', description: 'Ethereal background ambience', type: 'audio', model_id: 'lyria-3-pro-preview' },
  { id: 'music-light-sting', stage: 'F', category: 'music', name: 'Music Light Sting', description: 'Positive stinger for Light faction', type: 'audio', model_id: 'lyria-3-clip-preview' },
  { id: 'music-dark-sting', stage: 'F', category: 'music', name: 'Music Dark Sting', description: 'Negative stinger for Dark faction', type: 'audio', model_id: 'lyria-3-clip-preview' },
  { id: 'sfx-invalid', stage: 'G', category: 'sfx', name: 'SFX Invalid', description: 'Error/invalid action sound', type: 'audio' },
  { id: 'sfx-move-fly', stage: 'G', category: 'sfx', name: 'SFX Move Fly', description: 'Flying unit movement sound', type: 'audio' },
  { id: 'sfx-teleport', stage: 'G', category: 'sfx', name: 'SFX Teleport', description: 'Teleportation sound effect', type: 'audio' },
  { id: 'sfx-projectile', stage: 'G', category: 'sfx', name: 'SFX Projectile', description: 'Ranged attack projectile sound', type: 'audio' },
  { id: 'sfx-impact', stage: 'G', category: 'sfx', name: 'SFX Impact', description: 'General impact sound effect', type: 'audio' },
  { id: 'sfx-revive', stage: 'G', category: 'sfx', name: 'SFX Revive', description: 'Unit revival sound effect', type: 'audio' },
  { id: 'sfx-healing-pulse', stage: 'G', category: 'sfx', name: 'SFX Healing Pulse', description: 'Healing pulse sound effect', type: 'audio' },
  { id: 'sfx-luminance-shift', stage: 'G', category: 'sfx', name: 'SFX Luminance Shift', description: 'Luminance change sound effect', type: 'audio' },
  { id: 'sfx-imprison-apply', stage: 'G', category: 'sfx', name: 'SFX Imprison Apply', description: 'Imprisonment start sound', type: 'audio' },
  { id: 'sfx-imprison-release', stage: 'G', category: 'sfx', name: 'SFX Imprison Release', description: 'Imprisonment end sound', type: 'audio' },
  { id: 'sfx-barrier-phase', stage: 'G', category: 'sfx', name: 'SFX Barrier Phase', description: 'Barrier phasing sound', type: 'audio' },
  { id: 'sfx-barrier-collision', stage: 'G', category: 'sfx', name: 'SFX Barrier Collision', description: 'Collision with barrier sound', type: 'audio' },
  { id: 'sfx-dodge', stage: 'G', category: 'sfx', name: 'SFX Dodge', description: 'Unit dodge sound effect', type: 'audio' },
  { id: 'sfx-death-light', stage: 'G', category: 'sfx', name: 'SFX Death Light', description: 'Light faction death sound', type: 'audio' },
  { id: 'sfx-death-dark', stage: 'G', category: 'sfx', name: 'SFX Death Dark', description: 'Dark faction death sound', type: 'audio' },
  { id: 'voice-battle', stage: 'H', category: 'voice', name: 'Voice Battle', description: 'Announcer: "Battle Begins!"', type: 'audio', model_id: 'gemini-2.5-flash-preview-tts' },
  { id: 'voice-victory', stage: 'H', category: 'voice', name: 'Voice Victory', description: 'Announcer: "Victory!"', type: 'audio', model_id: 'gemini-2.5-flash-preview-tts' },
  { id: 'voice-defeat', stage: 'H', category: 'voice', name: 'Voice Defeat', description: 'Announcer: "Defeat!"', type: 'audio', model_id: 'gemini-2.5-flash-preview-tts' },
];
